<br />
<font size='1'><table class='xdebug-error xe-uncaught-exception' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Fatal error: Uncaught Error: Call to undefined function esc_html__() in /Users/ahmedmannan/Local Sites/jaguarlimo/app/public/wp-content/plugins/wpforms-lite/includes/admin/class-about.php on line <i>77</i></th></tr>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Error: Call to undefined function esc_html__() in /Users/ahmedmannan/Local Sites/jaguarlimo/app/public/wp-content/plugins/wpforms-lite/includes/admin/class-about.php on line <i>77</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0001</td><td bgcolor='#eeeeec' align='right'>406408</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='/Users/ahmedmannan/Local Sites/jaguarlimo/app/public/wp-content/plugins/wpforms-lite/includes/admin/class-about.php' bgcolor='#eeeeec'>.../class-about.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0001</td><td bgcolor='#eeeeec' align='right'>406488</td><td bgcolor='#eeeeec'>WPForms_About->__construct(  )</td><td title='/Users/ahmedmannan/Local Sites/jaguarlimo/app/public/wp-content/plugins/wpforms-lite/includes/admin/class-about.php' bgcolor='#eeeeec'>.../class-about.php<b>:</b>1125</td></tr>
</table></font>
