<br />
<font size='1'><table class='xdebug-error xe-warning' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Warning: Use of undefined constant WPFORMS_PLUGIN_DIR - assumed 'WPFORMS_PLUGIN_DIR' (this will throw an Error in a future version of PHP) in /Users/ahmedmannan/Local Sites/jaguarlimo/app/public/wp-content/plugins/wpforms-lite/includes/class-fields.php on line <i>30</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0001</td><td bgcolor='#eeeeec' align='right'>405352</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='/Users/ahmedmannan/Local Sites/jaguarlimo/app/public/wp-content/plugins/wpforms-lite/includes/class-fields.php' bgcolor='#eeeeec'>.../class-fields.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0001</td><td bgcolor='#eeeeec' align='right'>405392</td><td bgcolor='#eeeeec'>WPForms_Fields->__construct(  )</td><td title='/Users/ahmedmannan/Local Sites/jaguarlimo/app/public/wp-content/plugins/wpforms-lite/includes/class-fields.php' bgcolor='#eeeeec'>.../class-fields.php<b>:</b>89</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.0001</td><td bgcolor='#eeeeec' align='right'>405392</td><td bgcolor='#eeeeec'>WPForms_Fields->init(  )</td><td title='/Users/ahmedmannan/Local Sites/jaguarlimo/app/public/wp-content/plugins/wpforms-lite/includes/class-fields.php' bgcolor='#eeeeec'>.../class-fields.php<b>:</b>19</td></tr>
</table></font>
<br />
<font size='1'><table class='xdebug-error xe-warning' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Warning: require_once(WPFORMS_PLUGIN_DIRincludes/fields/class-base.php): failed to open stream: No such file or directory in /Users/ahmedmannan/Local Sites/jaguarlimo/app/public/wp-content/plugins/wpforms-lite/includes/class-fields.php on line <i>30</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0001</td><td bgcolor='#eeeeec' align='right'>405352</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='/Users/ahmedmannan/Local Sites/jaguarlimo/app/public/wp-content/plugins/wpforms-lite/includes/class-fields.php' bgcolor='#eeeeec'>.../class-fields.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0001</td><td bgcolor='#eeeeec' align='right'>405392</td><td bgcolor='#eeeeec'>WPForms_Fields->__construct(  )</td><td title='/Users/ahmedmannan/Local Sites/jaguarlimo/app/public/wp-content/plugins/wpforms-lite/includes/class-fields.php' bgcolor='#eeeeec'>.../class-fields.php<b>:</b>89</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.0001</td><td bgcolor='#eeeeec' align='right'>405392</td><td bgcolor='#eeeeec'>WPForms_Fields->init(  )</td><td title='/Users/ahmedmannan/Local Sites/jaguarlimo/app/public/wp-content/plugins/wpforms-lite/includes/class-fields.php' bgcolor='#eeeeec'>.../class-fields.php<b>:</b>19</td></tr>
</table></font>
<br />
<font size='1'><table class='xdebug-error xe-fatal-error' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Fatal error: require_once(): Failed opening required 'WPFORMS_PLUGIN_DIRincludes/fields/class-base.php' (include_path='.:/usr/share/php:/www/wp-content/pear') in /Users/ahmedmannan/Local Sites/jaguarlimo/app/public/wp-content/plugins/wpforms-lite/includes/class-fields.php on line <i>30</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0001</td><td bgcolor='#eeeeec' align='right'>405352</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='/Users/ahmedmannan/Local Sites/jaguarlimo/app/public/wp-content/plugins/wpforms-lite/includes/class-fields.php' bgcolor='#eeeeec'>.../class-fields.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0001</td><td bgcolor='#eeeeec' align='right'>405392</td><td bgcolor='#eeeeec'>WPForms_Fields->__construct(  )</td><td title='/Users/ahmedmannan/Local Sites/jaguarlimo/app/public/wp-content/plugins/wpforms-lite/includes/class-fields.php' bgcolor='#eeeeec'>.../class-fields.php<b>:</b>89</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.0001</td><td bgcolor='#eeeeec' align='right'>405392</td><td bgcolor='#eeeeec'>WPForms_Fields->init(  )</td><td title='/Users/ahmedmannan/Local Sites/jaguarlimo/app/public/wp-content/plugins/wpforms-lite/includes/class-fields.php' bgcolor='#eeeeec'>.../class-fields.php<b>:</b>19</td></tr>
</table></font>
